/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#d9c0c6",
        "secondary": "#525a92",
        "on-secondary-fixed": "#0c154b",
        "on-error-container": "#93000a",
        "surface-container-highest": "#eddfe5",
        "primary": "#9b3e64",
        "on-tertiary-fixed-variant": "#354c3b",
        "surface-container-low": "#fff0f6",
        "surface-container": "#f9eaf0",
        "surface-tint": "#9b3e64",
        "background": "#fff8f9",
        "tertiary-fixed": "#cee9d3",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb0ca",
        "primary-fixed": "#ffd9e3",
        "surface-variant": "#eddfe5",
        "surface-container-high": "#f3e4ea",
        "on-tertiary-fixed": "#092012",
        "surface-dim": "#e5d6dc",
        "inverse-surface": "#362e33",
        "on-tertiary-container": "#324939",
        "secondary-fixed": "#dfe0ff",
        "outline": "#867277",
        "on-surface-variant": "#544247",
        "tertiary-fixed-dim": "#b3cdb7",
        "primary-container": "#ff8fb8",
        "inverse-primary": "#ffb0ca",
        "on-primary-fixed-variant": "#7d264c",
        "on-secondary-container": "#444c83",
        "on-primary": "#ffffff",
        "surface": "#fff8f9",
        "secondary-container": "#b8c0ff",
        "on-primary-container": "#7a2349",
        "on-secondary-fixed-variant": "#3a4379",
        "on-surface": "#21191e",
        "on-error": "#ffffff",
        "tertiary": "#4c6452",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#fcedf3",
        "error-container": "#ffdad6",
        "on-background": "#21191e",
        "surface-bright": "#fff8f9",
        "on-secondary": "#ffffff",
        "tertiary-container": "#9eb8a3",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#bbc3ff",
        "on-primary-fixed": "#3e001f"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "heart-padding-md": "24px",
        "heart-padding-lg": "40px",
        "max-width-desktop": "1200px",
        "heart-padding-sm": "12px",
        "ribbon-gutter": "20px",
        "bubble-unit": "8px"
      },
      fontFamily: {
        sans: ["var(--font-be-vietnam-pro)", "sans-serif"],
        display: ["var(--font-plus-jakarta-sans)", "sans-serif"],
        heading: ["var(--font-plus-jakarta-sans)", "sans-serif"],
        quicksand: ["var(--font-quicksand)", "sans-serif"]
      }
    },
  },
  plugins: [],
}
